name: Build
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          df -h
      - name: Install dependencies
        run: bash script/linux
      - run: cargo build
        env:
          CARGO_BUILD_JOBS: 2
      - uses: actions/upload-artifact@v4
        with:
          name: void-binary
          path: target/debug/zed